/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as PrecosRouteImport } from './routes/precos'
import { Route as AuthenticatedEstudioRouteImport } from './routes/_authenticated/estudio'
import { Route as AuthenticatedGaleriaRouteImport } from './routes/_authenticated/galeria'
import { Route as AuthenticatedMinhasCenasRouteImport } from './routes/_authenticated/minhas-cenas'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const PrecosRoute = PrecosRouteImport.update({
  id: '/precos',
  path: '/precos',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedEstudioRoute = AuthenticatedEstudioRouteImport.update({
  id: '/estudio',
  path: '/estudio',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGaleriaRoute = AuthenticatedGaleriaRouteImport.update({
  id: '/galeria',
  path: '/galeria',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMinhasCenasRoute =
  AuthenticatedMinhasCenasRouteImport.update({
    id: '/minhas-cenas',
    path: '/minhas-cenas',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/precos': typeof PrecosRoute
  '/estudio': typeof AuthenticatedEstudioRoute
  '/galeria': typeof AuthenticatedGaleriaRoute
  '/minhas-cenas': typeof AuthenticatedMinhasCenasRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/precos': typeof PrecosRoute
  '/estudio': typeof AuthenticatedEstudioRoute
  '/galeria': typeof AuthenticatedGaleriaRoute
  '/minhas-cenas': typeof AuthenticatedMinhasCenasRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/precos': typeof PrecosRoute
  '/_authenticated/estudio': typeof AuthenticatedEstudioRoute
  '/_authenticated/galeria': typeof AuthenticatedGaleriaRoute
  '/_authenticated/minhas-cenas': typeof AuthenticatedMinhasCenasRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/auth' | '/precos' | '/estudio' | '/galeria' | '/minhas-cenas'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth' | '/precos' | '/estudio' | '/galeria' | '/minhas-cenas'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/precos'
    | '/_authenticated/estudio'
    | '/_authenticated/galeria'
    | '/_authenticated/minhas-cenas'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  PrecosRoute: typeof PrecosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/precos': {
      id: '/precos'
      path: '/precos'
      fullPath: '/precos'
      preLoaderRoute: typeof PrecosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/estudio': {
      id: '/_authenticated/estudio'
      path: '/estudio'
      fullPath: '/estudio'
      preLoaderRoute: typeof AuthenticatedEstudioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/galeria': {
      id: '/_authenticated/galeria'
      path: '/galeria'
      fullPath: '/galeria'
      preLoaderRoute: typeof AuthenticatedGaleriaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/minhas-cenas': {
      id: '/_authenticated/minhas-cenas'
      path: '/minhas-cenas'
      fullPath: '/minhas-cenas'
      preLoaderRoute: typeof AuthenticatedMinhasCenasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedEstudioRoute: typeof AuthenticatedEstudioRoute
  AuthenticatedGaleriaRoute: typeof AuthenticatedGaleriaRoute
  AuthenticatedMinhasCenasRoute: typeof AuthenticatedMinhasCenasRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedEstudioRoute: AuthenticatedEstudioRoute,
  AuthenticatedGaleriaRoute: AuthenticatedGaleriaRoute,
  AuthenticatedMinhasCenasRoute: AuthenticatedMinhasCenasRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  PrecosRoute: PrecosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
